#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/hongyundesk/rustdesk /usr/bin/hongyundesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/hongyundesk.service ]; then
			rm /etc/systemd/system/hongyundesk.service /usr/lib/systemd/system/hongyundesk.service /usr/lib/systemd/user/hongyundesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/hongyundesk/files/systemd/hongyundesk.service /usr/lib/systemd/system/hongyundesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload hongyundesk.service: Unit hongyundesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/hongyundesk.service:10: Executable path is not absolute: pkill -f "hongyundesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/hongyundesk.service
		fi
		systemctl daemon-reload
		systemctl enable hongyundesk
		systemctl start hongyundesk
	fi
fi
